services:
  app:
    build: .
    container_name: urlbackend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    working_dir: /src
    volumes:
      - ./:/src
    depends_on:
      - db
  db:
    image: postgres:14.5
    container_name: urldatabase
    environment:
      - POSTGRES_PASSWORD=passkey
    volumes:
      - psqlvol:/var/lib/postgresql/data
networks:
    default:
      name: urlnet
volumes:
  psqlvol:
    name: psqlvol
    external: true